[package]
name = "hello_world"
version = "0.1.0"
edition = "2024"

[dependencies]
clap.workspace = true
rand.workspace = true
anyhow.workspace = true
chrono.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
